### ISSUE TITLE
What does it take to enable LIDAR see through Terrain in Unity ? 

### ISSUE THREAD

**Issue by jediofgever** [RobotecAI/RobotecGPULidar#113]
Hello, 

I am using this AWSIM simulator and I believe the LIDAR plugin there is sourced from this repository. 

I generated a map where I have some Terrain, although the terrain has its collider, it seems that the LIDAR rays wont hit, hence no points are returned on the terrain.  

![Screenshot from 2023-03-14 02-10-01](https://user-images.githubusercontent.com/18460336/224872226-1d4d6b51-8c98-4f79-9778-41b130422fdd.png)

I was wondering whether it is possible to extend the plugin to also hit Terrains in Unity. 
Thank you for your time.

**Comment by prybicki** [comment]
Thank you, @jediofgever, for your suggestion. I think it is a good idea. I will consult this with AWSIM maintainers.

**Comment by jediofgever** [comment]
Thanks, @prybicki !, meanwhile a workaround for me was to convert terrain to mesh using some unity [script](https://github.com/burakdaskin/Terrain-To-Object-Exporter), but this is still troublesome because the exported mesh only includes ground, it excludes, for example, trees and other plants that are represented with terrain in Unity.

**Comment by prybicki** [comment]
@jediofgever Thanks for the ping. I talked to AWSIM maintainers and internally with my team.
- Currently, development for AWSIM is focused on other features to improve simulation realism. They acknowledge this is a nice feature; however, unfortunately, we may be able to start developing it in the fall/winter.
- Good implementation of such a feature is a challenging task since conversion from a height map to a mesh is (counterintuitively) not trivial, not to mention details such as trees, which can be instantiated deep inside the rendering pipeline on the GPU.
- Therefore, as of now, I can only recommend preparing the simulation scene in such a way that explicitly represents entities like trees and converting the terrain to a mesh.
